export const IMAGE_NAME = {
  CIRCLE_ARROW: "IMAGE_NAME__CIRCLE_ARROW",
  NINE_LINES_IN_SQUARE: "IMAGE_NAME__NINE_LINES_IN_SQUARE",
  LOGO: "IMAGE_NAME__LOGO",
  START: "IMAGE_NAME__START",
  LETTER_T_IN_SQUARE: "IMAGE_NAME__LETTER_T_IN_SQUARE",
  TWO_IMAGES: "IMAGE_NAME__TWO_IMAGES",
};
